Request "[EAG4-19]Creating QuickGame core implementation, fix tests"
group4-account/who-am-i pull request #4
Opened 2022-06-12 20:45 UTC by MarianDolynskyi

Reverts group4-account/who-am-i#3

2022-06-15 13:35 UTC, sokolruslan requested changes

2022-06-15 13:35 UTC, sokolruslan commented on src/main/java/com/eleks/academy/whoami/WhoAmIApplication.java
> +	@Bean
це можна видалити, там в загальному каналі в слаку є рішення від Nazar Svytak, як то фіксати без додавання біна

2022-06-15 13:35 UTC, sokolruslan commented on src/main/java/com/eleks/academy/whoami/model/request/NewGameRequest.java
> +}
додай новий рядок на 23 line,
git матюкається якщо файл закінчується не пустим рядком, а дужкою

2022-06-15 19:13 UTC, Gredgit commented on src/main/java/com/eleks/academy/whoami/controller/GameController.java
> +		return gameService.findAvailableQuickGame(player)
Мені здається тут пропущено `@Valid @RequestBody NewGameRequest gameRequest`. Я б залишив цей параметр тут, щоб в майбутньому можна було враховувати максимальну кількість гравців

2022-06-16 13:58 UTC, MarianDolynskyi commented on src/main/java/com/eleks/academy/whoami/controller/GameController.java
> +		return gameService.findAvailableQuickGame(player)
Зараз по вимогах не роблю, так як в нас гра всеодно лише 4 гравця зараз приймає, в майбутньому обов'язково

2022-06-16 14:04 UTC, merged